apiVersion: v1
kind: Pod
metadata:
  name: nginx-label
  labels:
    team: finance
    version: 1.4.1
    environment: production
spec:
  containers:
    - name:  nginx
      image: nginx
      ports:
        - containerPort: 8080